### ISSUE TITLE
Quitting a game and pressing play again puts the player on the title screen

### ISSUE THREAD

**Issue by Spectere** [SaxxonPike/roton#12]
When a game is quit, the player is kicked back to the title screen as expected. If they press P, they are placed on the title screen in the expected position with the stats that they had when they quit. If the player subsequently moves, quits from the title screen, and presses P again, they appear in the last position they were in.

This happens both when the player quits in mid-game as well as when they receive a game over.

**Comment by SaxxonPike** [comment]
This is due to the world not reloading from disk if the state is "dirty". I can grab it.

**Comment by SaxxonPike** [comment]
World reload is now implemented. Closing.
