### ISSUE TITLE
Players cannot touch monsters

### ISSUE THREAD

**Issue by Spectere** [SaxxonPike/roton#13]
Centipedes properly do damage if they run into the player, but currently the player cannot step onto a centipede as expected. Centipedes effective act as solid blocks, preventing the player from moving onto the tile.

**Comment by Spectere** [comment]
This seems to happen with all monsters. They lack an Interact() function.

**Comment by SaxxonPike** [comment]
The monsters need to have their behavior inherited from EnemyBehavior and that needs to have Interact implemented. I can take this one.
