### ISSUE TITLE
No Audio Plays

### ISSUE THREAD

**Issue by hegyak** [SaxxonPike/roton#24]
I can't seem to get any audio events to play.  Grabbing items, using Objects.

Easy Test.  Grab some Gems, Torches or use the Doorbell object in the ZZT Armory in Town of ZZT.

**Comment by Spectere** [comment]
Hey hegyak! Audio isn't implemented just yet, though it's pretty high up on our list. We'll update this issue when we have some sort of working implementation (likely OpenAL, since OpenTK has support for that).

**Comment by SaxxonPike** [comment]
Audio composer is in the works under the "composers" branch. Once this is finalized, we can hook up OpenTK and get some sound flowing!

**Comment by Spectere** [comment]
I'll snag this one. After the composers are ready I'll get started with this.

**Comment by SaxxonPike** [comment]
The 'testing' branch has audio playing. We're almost finished with it. There's Priority and the Be Noisy/Quiet switch to do yet.

**Comment by SaxxonPike** [comment]
Using SDL now. Audio is confirmed working on multiple platforms.
