### ISSUE TITLE
Space does not cause the player to shoot

### ISSUE THREAD

**Issue by Spectere** [SaxxonPike/roton#26]
Normally, pressing space causes the player to fire in the last direction that they moved in. This behavior is not currently implemented in Roton.

I'm not sure if any actual games implement this behavior, but this does break the following engines in the ZZT Encyclopedia (and may trip up people who are used to this behavior in genuine ZZT):

2ENCY3C -> 17. NO LIMITS ][ -> Space pressed
ZEOL-2 -> Space Bar

**Comment by SaxxonPike** [comment]
This is missing from `ActPlayer`. There are a couple other hotkeys missing (for example, `B` and its weird behavior that sets the currently pressed key to `space`, causing player clones to shoot). I can grab this.

**Comment by SaxxonPike** [comment]
I got this one.

**Comment by SaxxonPike** [comment]
Fixed in latest merge to `master`.
