### ISSUE TITLE
OTHERS and SELF targets include objects they shouldn't

### ISSUE THREAD

**Issue by hegyak** [SaxxonPike/roton#35]
Some objects in the game will change their appearance (into a different ASCII symbol) when interacted with.

How to recreate this:
Enter the Armory.
Push the Boulders Down on the top right.
Enter the Secret Path through the fake wall.
Push/Interact with the 4th music note.  It should change.

If it doesn't change, try the other notes.  One of them should change, and if you follow the pattern of the Blues man when he does his song, the notes should change.  If you get the pattern wrong, the notes revert to their original appearance.

**Comment by SaxxonPike** [comment]
I got this one.

**Comment by SaxxonPike** [comment]
Verified that the objects do not change in TOWN. The sequence for this puzzle is 4, 1, 5, 2, 3. In fact, this puzzle cannot be completed even if you do get the correct sequence.

**Comment by SaxxonPike** [comment]
I figured out the bug. The OTHERS and SELF targets were not working correctly. This meant that touching any of the notes *did* correctly change the character, but it was immediately being changed back because of how they were looping back to the start of the code (which resets the character.)

**Comment by hegyak** [comment]
Confirmed this has been corrected in:
https://github.com/SaxxonPike/roton/commit/da4e74834ab60ae675f4e3422605d31505db23f4

The puzzle can be completed in the House of Blues and the Blues man moves when the puzzle is completed.
