### ISSUE TITLE
Be Quiet and Be Noisy issues

### ISSUE THREAD

**Issue by hegyak** [SaxxonPike/roton#36]
Tested against:
https://github.com/SaxxonPike/roton/commit/dd5f35f54b636d8cfc4a558daae51472e6416538

Telling the game Be Quiet (B) doesn't actually set the game to be quiet.
To recreate this:
Start Town of ZZT
set the game to Be Quiet, then interact with the sign.
You should not hear some music play but it does.

A more important issue is when a jingle or music queue is played and you set the game to Be Quiet, the note currently being played will continue to be played.

To recreate this:
Enter the Armory in the Town of ZZT
Interact with the doorbell for the Guardian of the Key.
When the Guardian says "Go away, Cretin!"
Set the game to Be Quiet (B).  The game will continuously play the note(s) until you change boards.

**Comment by SaxxonPike** [comment]
I'll take this one.

**Comment by SaxxonPike** [comment]
@hegyak There were some updates last night that address problems with sound specifically, maybe try the latest `master`?

**Comment by hegyak** [comment]
https://github.com/SaxxonPike/roton/commit/fc73ec1593c3df573ffba7147a88a66877244076
Gives me the following error when trying to compile:

`Error	CS1503	Argument 1: cannot convert from 'Roton.Emulation.Data.Impl.RandomState' to 'System.Lazy<Roton.Emulation.Data.IConfig>'	Roton	*FULL PATH TRIMMED*\roton-master\Roton\Emulation\Core\Impl\Random.cs	16	Active`

**Comment by hegyak** [comment]
The audio bug I experienced has been corrected in or possibly an earlier commit: https://github.com/SaxxonPike/roton/commit/8ed6b066ecaf106d6a2a17e4159c8b46ddf494a7

The Compile bug I mentioned above however, is still happening.

By using Visual Studio's auto correct function, I was able to get the Solution to Compile again.

Changes made to Roton\Emulation\Core\Impl\Randomizer.cs and surrounding code to act as a refrence:

`private readonly Lazy<IRandomState> _randomState;
        private RandomState randomState;

        private IRandomState RandomState => _randomState.Value;

        public Randomizer(Lazy<IConfig> config)
        {
            _randomState = new Lazy<IRandomState>(() => 
                config.Value.RandomSeed.HasValue ? 
                new RandomState(config.Value.RandomSeed.Value) :
                new RandomState());
        }

        public Randomizer(RandomState randomState)
        {
            this.randomState = randomState;
        }

        public int GetNext(int exclusiveUpperBound)`

This probably isn't an elegant fix, but Roton does compile and appears to be working again.

Edit:
Added file name of edited/changed file.

**Comment by SaxxonPike** [comment]
There were some changes that didn't get committed to `lazy` and instead ended up in `master`. I think the latest merge should resolve the issue.

**Comment by hegyak** [comment]
This has been corrected.

Tested against:
https://github.com/SaxxonPike/roton/commit/da4e74834ab60ae675f4e3422605d31505db23f4
