### ISSUE TITLE
All Boards are Re-Enter when Zapped

### ISSUE THREAD

**Issue by hegyak** [SaxxonPike/roton#37]
All Boards in the Town of ZZT act like the flag "Re-Enter when Zapped" is true.

To Recreate this:
Start Town of ZZT
Go to the south board with the Centipedes in it.
Get hit (Zapped).
You respawn at the top of the board.

**Comment by SaxxonPike** [comment]
I got this.

**Comment by SaxxonPike** [comment]
I verified that the board titled "Bug Maze" is not configured for "restart on zap". I then started the world and went south, stepped into some of the centipedes, and did not see the same thing happen. Can you send the version of TOWN.ZZT you're using, or tell us where you got it from?

**Comment by hegyak** [comment]
I am guessing something went wrong but I checked it again, and my bug is corrected.  I didn't use a Town.zzt file with Roton.
