### ISSUE TITLE
Missing resource: ORDER.HLP

### ISSUE THREAD

**Issue by hegyak** [SaxxonPike/roton#42]
In the Town of ZZT, enter the Cave to the East of the Starting Board.

You can use cheats to make it easier (-Dark) on both cave boards.  You need to either have a Purple Key or you can Zap the Door away.  Interact with the Scroll in the Upper board and at the bottom of the scroll, there is an item "Order Form" Select that option to get the error.

**Comment by SaxxonPike** [comment]
We just lack the order form entirely. :) Maybe we can add a funny one as an easter egg.

**Comment by SaxxonPike** [comment]
Should be addressed by #45. But we will want to fill it in with something later.

**Comment by SaxxonPike** [comment]
Closing this one because the missing file is fixed. #46 will address the content in the future.
