### ISSUE TITLE
World selector is not implemented

### ISSUE THREAD

**Issue by hegyak** [SaxxonPike/roton#43]
Roton/Lyon wants to load Town of ZZT (Town.zzt) and nothing else.

However, if there's a zzt world with the name town.zzt, Roton/Lyon will load that world instead.  However, quitting the world and going back to the title screen, breaks Roton/Lyon.

To recreate the Wrong World Bug (I can't think of an accurate name):
Rename any world except Town of ZZT, to town.zzt  I chose City of ZZT
Load the "Town" World
Quit the world
The client says, "CITY" instead of "TOWN"
You can't load another World file, or play the currently loaded World.

**Comment by SaxxonPike** [comment]
This is known behavior. ZZT will use the internal file name (inside the world file) to reload worlds. This is demonstrated in the ZZT Encyclopedia (newworld.zzt)

However, the World selector is *not* implemented, so I'll put that functionality under this issue.

**Comment by SaxxonPike** [comment]
World selector is implemented for now, however it does not allow traversing directories just yet. I'm going to separate that issue.
