### ISSUE TITLE
In-game help is shown instead of high scores on the title screen

### ISSUE THREAD

**Issue by hegyak** [SaxxonPike/roton#44]
When you push H on the Title screen for a World, it shows the Help menu instead of the High Score list.

To recreate this:
Start Lyon
Load Town of ZZT
Press H

**Comment by SaxxonPike** [comment]
Legit bug. We don't have high scores implemented yet.

**Comment by SaxxonPike** [comment]
Using 'missing feature' instead of 'bug' as the behavior does not yet exist.

**Comment by SaxxonPike** [comment]
Should be resolved with #47.

**Comment by hegyak** [comment]
Confirmed Resolved.  Welcome back High Scores.
