### ISSUE TITLE
Scripting not working

### ISSUE THREAD

**Issue by hegyak** [SaxxonPike/roton#6]
Issue:
Load any ZZT file that uses a script.  Like Caves of ZZT or Mission: Enigma.  The Caves of ZZT should animate the title.  Mission: Enigma's title should have a fancy demonstration.

**Comment by SaxxonPike** [comment]
I'll have a look.

**Comment by SaxxonPike** [comment]
Looks like a lot of the OOP scripting is simply absent. It needs to get ported from the old Roton codebase yet. I'm going to revisit this project in the next couple months and hopefully get feature parity.

**Comment by SaxxonPike** [comment]
Mission: Enigma's title screen now plays through fully as of the latest commit.

Video proof here: https://www.youtube.com/watch?v=rRQw8H6sk4I

There's work to be done on the long message display, but that will be considered a separate issue. Scripting itself should be working now.
